mediaelement.formatter.media:
  type: mapping
  label: 'MediaElement.js format settings'
  mapping:
    download_link:
      type: boolean
      label: 'Download Link'
    download_text:
      type: string
      label: 'Download Text'

field.formatter.settings.mediaelement_file_video:
  type: mediaelement.formatter.media
  label: 'MediaElement.js Video formatter settings'
  mapping:
    poster_image_field:
      type: string
      label: 'Poster Image Field'
    poster_image_style:
      type: string
      label: 'Poster Image Style'

field.formatter.settings.mediaelement_file_audio:
  type: mediaelement.formatter.media
  label: 'MediaElement.js Audio formatter settings'

mediaelement.settings:
  type: config_object
  label: 'MediaElement Settings'
  mapping:
    library_source:
      type: string
      label: 'Library Source'
    library_version:
      type: string
      label: 'Library Version'
    attach_sitewide:
      type: integer
      label: 'Attach sitewide'
    class_prefix:
      type: string
      label: 'Class Prefix'
    set_dimensions:
      type: integer
      label: 'Set Dimensions'
    default_video_width:
      type: integer
      label: 'Default Video Width'
    default_video_height:
      type: integer
      label: 'Default Video Height'
    default_audio_width:
      type: integer
      label: 'Default Audio Width'
    default_audio_height:
      type: integer
      label: 'Default Audio Height'
    video_width:
      type: integer
      label: 'Video Width'
    video_height:
      type: integer
      label: 'Video Height'
    audio_width:
      type: integer
      label: 'Audio Width'
    audio_height:
      type: integer
      label: 'Audio Height'
